# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.githubusercontent.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: Bootstrap

# Adapt as necessary starting from here

platform: x64

environment:
  global:
    WARNINGS_ARE_ERRORS: 0

  matrix:
    - R_VERSION: devel
      R_ARCH: x64
      USE_RTOOLS: true
      BIOC_USE_DEVEL: "TRUE"

    - R_VERSION: release
      R_ARCH: x64
      USE_RTOOLS: true
      BIOC_USE_DEVEL: "TRUE"

build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh bioc_install S4Vectors
  - travis-tool.sh bioc_install piano
  - travis-tool.sh bioc_install lsa
  - travis-tool.sh bioc_install SummarizedExperiment
  - travis-tool.sh bioc_install GenomeInfoDbData
  - travis-tool.sh bioc_install GenomeInfoDb

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs


artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
